FROM node:22.11

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /client

COPY package.json ./
COPY package-lock.json ./

RUN npm ci

COPY . .
EXPOSE 3000

# run the nextjs dev server
CMD ["npm", "run", "dev"]