services:
  client:
    build:
      # use client's own dockerfile instead of build info in here
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0' # Grant docker access to USB-to-serial device


  # something like this:
  # db:
  # image: postgres:13
  # environment:
  #   POSTGRES_USER: postgres
  #   POSTGRES_PASSWORD: example
  #   POSTGRES_DB: mydatabase
  # volumes:
  #   - pgdata:/var/lib/postgresql/data
  # ports:
  #   - "1234:1234"
