services:
  client:
    build:
      # use client's own dockerfile instead of build info in here
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      # Internal network address to reach the api
      - API_URL=http://api:3001
      - IS_DOCKER=true # Identify docker to make changes and re-compilation possible
    depends_on:
      - api
    volumes:
      - ./client:/client
      - /client/node_modules # This excludes node_modules being mounted
      - /client/.next # Don't want my local .next being mounted

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      DB_PORT: 5432
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db # Ensure db starts first
    volumes:
      - ./api:/api
      - /api/node_modules # Exclude this directory from mount

  db:
    image: postgres:13
    environment:
      NODE_ENV: development
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/db-data-dev:/var/lib/postgresql/data # Persistent DB data across container start-ups
      - ./db/db-init:/docker-entrypoint-initdb.d # Runs initial scripts to create + insert the initial DB data
      - ./db/db-init/fonts.csv:/fonts.csv # Mount fonts.csv for loading
    ports:
      - '5432:5432'
